package com.knvovk.gamehub.domain.models.platform

enum class Platform(val id: Int, val _name: String) {
    XBOX_ONE(id = 1, _name = "Xbox One"),
    IOS(id = 3, _name = "iOS"),
    PC(id = 4, _name = "PC"),
    MACOS(id = 5, _name = "macOS"),
    LINUX(id = 6, _name = "Linux"),
    NINTENDO_SWITCH(id = 7, _name = "Nintendo Switch"),
    NINTENDO_3DS(id = 8, _name = "Nintendo 3DS"),
    NINTENDO_DS(id = 9, _name = "Nintendo DS"),
    WII_U(id = 10, _name = "Wii U"),
    WII(id = 11, _name = "Wii"),
    NEO_GEO(id = 12, _name = "Neo Geo"),
    NINTENDO_DSI(id = 13, _name = "Nintendo DSi"),
    XBOX_360(id = 14, _name = "Xbox 360"),
    PLAYSTATION_2(id = 15, _name = "PlayStation 2"),
    PLAYSTATION_3(id = 16, _name = "PlayStation 3"),
    PSP(id = 17, _name = "PSP"),
    PLAYSTATION_4(id = 18, _name = "PlayStation 4"),
    PS_VITA(id = 19, _name = "PS Vita"),
    ANDROID(id = 21, _name = "Android"),
    ATARI_FLASHBACK(id = 22, _name = "Atari Flashback"),
    ATARI_2600(id = 23, _name = "Atari 2600"),
    GAME_BOY_ADVANCE(id = 24, _name = "Game Boy Advance"),
    ATARI_8_BIT(id = 25, _name = "Atari 8-bit"),
    GAME_BOY(id = 26, _name = "Game Boy"),
    PLAYSTATION(id = 27, _name = "PlayStation"),
    ATARI_7800(id = 28, _name = "Atari 7800"),
    ATARI_5200(id = 31, _name = "Atari 5200"),
    ATARI_ST(id = 34, _name = "Atari ST"),
    APPLE_II(id = 41, _name = "Apple II"),
    GAME_BOY_COLOR(id = 43, _name = "Game Boy Color"),
    ATARI_LYNX(id = 46, _name = "Atari Lynx"),
    NES(id = 49, _name = "NES"),
    ATARI_XEGS(id = 50, _name = "Atari XEGS"),
    CLASSIC_MACINTOSH(id = 55, _name = "Classic Macintosh"),
    SEGA_MASTER_SYSTEM(id = 74, _name = "SEGA Master System"),
    GAME_GEAR(id = 77, _name = "Game Gear"),
    SNES(id = 79, _name = "SNES"),
    XBOX(id = 80, _name = "Xbox"),
    NINTENDO_64(id = 83, _name = "Nintendo 64"),
    GAME_CUBE(id = 105, _name = "GameCube"),
    DREAMCAST(id = 106, _name = "Dreamcast"),
    SEGA_SATURN(id = 107, _name = "SEGA Saturn"),
    THREE_DO(id = 111, _name = "3DO"),
    JAGUAR(id = 112, _name = "Jaguar"),
    SEGA_32_X(id = 117, _name = "SEGA 32X"),
    SEGA_CD(id = 119, _name = "SEGA CD"),
    COMMODORE_AMIGA(id = 166, _name = "Commodore / Amiga"),
    GENESIS(id = 167, _name = "Genesis"),
    WEB(id = 171, _name = "Web"),
    XBOX_SERIES_X(id = 186, _name = "Xbox Series X"),
    PLAYSTATION_5(id = 187, _name = "PlayStation 5"),
    NONE(id = -1, _name = "");

    companion object {
        fun of(id: Int): Platform = values().firstOrNull { it.id == id } ?: NONE
    }
}