package com.knvovk.gamehub.domain.models.platform

enum class Platform(val id: Int, val name_: String) {
    XBOX_ONE(id = 1, name_ = "Xbox One"),
    IOS(id = 3, name_ = "iOS"),
    PC(id = 4, name_ = "PC"),
    MACOS(id = 5, name_ = "macOS"),
    LINUX(id = 6, name_ = "Linux"),
    NINTENDO_SWITCH(id = 7, name_ = "Nintendo Switch"),
    NINTENDO_3DS(id = 8, name_ = "Nintendo 3DS"),
    NINTENDO_DS(id = 9, name_ = "Nintendo DS"),
    WII_U(id = 10, name_ = "Wii U"),
    WII(id = 11, name_ = "Wii"),
    NEO_GEO(id = 12, name_ = "Neo Geo"),
    NINTENDO_DSI(id = 13, name_ = "Nintendo DSi"),
    XBOX_360(id = 14, name_ = "Xbox 360"),
    PLAYSTATION_2(id = 15, name_ = "PlayStation 2"),
    PLAYSTATION_3(id = 16, name_ = "PlayStation 3"),
    PSP(id = 17, name_ = "PSP"),
    PLAYSTATION_4(id = 18, name_ = "PlayStation 4"),
    PS_VITA(id = 19, name_ = "PS Vita"),
    ANDROID(id = 21, name_ = "Android"),
    ATARI_FLASHBACK(id = 22, name_ = "Atari Flashback"),
    ATARI_2600(id = 23, name_ = "Atari 2600"),
    GAME_BOY_ADVANCE(id = 24, name_ = "Game Boy Advance"),
    ATARI_8_BIT(id = 25, name_ = "Atari 8-bit"),
    GAME_BOY(id = 26, name_ = "Game Boy"),
    PLAYSTATION(id = 27, name_ = "PlayStation"),
    ATARI_7800(id = 28, name_ = "Atari 7800"),
    ATARI_5200(id = 31, name_ = "Atari 5200"),
    ATARI_ST(id = 34, name_ = "Atari ST"),
    APPLE_II(id = 41, name_ = "Apple II"),
    GAME_BOY_COLOR(id = 43, name_ = "Game Boy Color"),
    ATARI_LYNX(id = 46, name_ = "Atari Lynx"),
    NES(id = 49, name_ = "NES"),
    ATARI_XEGS(id = 50, name_ = "Atari XEGS"),
    CLASSIC_MACINTOSH(id = 55, name_ = "Classic Macintosh"),
    SEGA_MASTER_SYSTEM(id = 74, name_ = "SEGA Master System"),
    GAME_GEAR(id = 77, name_ = "Game Gear"),
    SNES(id = 79, name_ = "SNES"),
    XBOX(id = 80, name_ = "Xbox"),
    NINTENDO_64(id = 83, name_ = "Nintendo 64"),
    GAME_CUBE(id = 105, name_ = "GameCube"),
    DREAMCAST(id = 106, name_ = "Dreamcast"),
    SEGA_SATURN(id = 107, name_ = "SEGA Saturn"),
    THREE_DO(id = 111, name_ = "3DO"),
    JAGUAR(id = 112, name_ = "Jaguar"),
    SEGA_32_X(id = 117, name_ = "SEGA 32X"),
    SEGA_CD(id = 119, name_ = "SEGA CD"),
    COMMODORE_AMIGA(id = 166, name_ = "Commodore / Amiga"),
    GENESIS(id = 167, name_ = "Genesis"),
    WEB(id = 171, name_ = "Web"),
    XBOX_SERIES_X(id = 1, name_ = "Xbox Series X"),
    UNKNOWN(id = -1, name_ = "Unknown");

    companion object {
        fun of(id: Int): Platform = values().firstOrNull { it.id == id } ?: UNKNOWN
    }
}